name: aless-merkatu

services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aless-merkatu-back:latest
    container_name: aless-back
    ports:
      - "3001:3001"
    restart: unless-stopped

  front:
    build:
      context: ./vite-json-html-starter
      dockerfile: Dockerfile
    image: aless-merkatu-front:latest
    container_name: aless-front
    ports:
      - "5173:3000"
    depends_on:
      - back
    restart: unless-stopped
