apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: merkatu
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= # Base64 for "postgres"
  DB_PASSWORD: MTIzNDU= # Base64 for "12345"
  DB_NAME: bWVyY2F0dQ== # Base64 for "merkatu"
